//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cash
    {
        public int ID { get; set; }
        public double Debit { get; set; }
        public double Credit { get; set; }
        public System.DateTime Date { get; set; }
        public string Description { get; set; }
        public double Balance { get; set; }
    }
}
