//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerDue
    {
        public int ID { get; set; }
        public int Customer_FK { get; set; }
        public double Amount { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
