//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expens
    {
        public int ID { get; set; }
        public int Exp_Category_FK { get; set; }
        public string PaymentMethod { get; set; }
        public string BankName { get; set; }
        public string Description { get; set; }
        public System.DateTime Date { get; set; }
        public double Amount { get; set; }
    
        public virtual Expense_Category Expense_Category { get; set; }
    }
}
