//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class POS_dbEntities : DbContext
    {
        public POS_dbEntities()
            : base("name=POS_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BankRecord> BankRecords { get; set; }
        public virtual DbSet<Bank> Banks { get; set; }
        public virtual DbSet<Cash> Cashes { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<CustomerDue> CustomerDues { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Expense_Category> Expense_Categories { get; set; }
        public virtual DbSet<Expens> Expenses { get; set; }
        public virtual DbSet<Fix_Asset> Fix_Assets { get; set; }
        public virtual DbSet<Log> Logs { get; set; }
        public virtual DbSet<Payment> Payments { get; set; }
        public virtual DbSet<PaymentsLedger> PaymentsLedgers { get; set; }
        public virtual DbSet<Product_Stock> Product_Stocks { get; set; }
        public virtual DbSet<Product_Sub_Category> Product_Sub_Categories { get; set; }
        public virtual DbSet<ProductCompany> ProductCompanies { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Products_Category> Products_Categories { get; set; }
        public virtual DbSet<Purchase> Purchases { get; set; }
        public virtual DbSet<PurchReturn> PurchReturns { get; set; }
        public virtual DbSet<Recieving> Recievings { get; set; }
        public virtual DbSet<rpt_Bank> rpt_Bank { get; set; }
        public virtual DbSet<rpt_ProfitLoss> rpt_ProfitLoss { get; set; }
        public virtual DbSet<rpt_Purchases> rpt_Purchases { get; set; }
        public virtual DbSet<rpt_Sale> rpt_Sale { get; set; }
        public virtual DbSet<Salary> Salaries { get; set; }
        public virtual DbSet<Sale> Sales { get; set; }
        public virtual DbSet<Supplier> Suppliers { get; set; }
        public virtual DbSet<SupplierDue> SupplierDues { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
