//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Product_Stock = new HashSet<Product_Stock>();
            this.Purchases = new HashSet<Purchase>();
            this.PurchReturns = new HashSet<PurchReturn>();
            this.Sales = new HashSet<Sale>();
        }
    
        public int Product_ID { get; set; }
        public string Name { get; set; }
        public int Product_Sub_Category_FK { get; set; }
        public double Purchase_Cost { get; set; }
        public double Tax { get; set; }
        public double Sale_Cost { get; set; }
        public string Barcode_Value { get; set; }
        public int Product_Company_FK { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product_Stock> Product_Stock { get; set; }
        public virtual Product_Sub_Category Product_Sub_Category { get; set; }
        public virtual ProductCompany ProductCompany { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Purchase> Purchases { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchReturn> PurchReturns { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sale> Sales { get; set; }
    }
}
