//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recieving
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Recieving()
        {
            this.Recievings1 = new HashSet<Recieving>();
        }
    
        public int ID { get; set; }
        public int Customer_FK { get; set; }
        public string PaymentMethod { get; set; }
        public string Description { get; set; }
        public System.DateTime Date { get; set; }
        public double Openning { get; set; }
        public double Amount { get; set; }
        public double Remaining { get; set; }
        public int Invoice { get; set; }
        public int User_FK { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Recieving> Recievings1 { get; set; }
        public virtual Recieving Recieving1 { get; set; }
        public virtual User User { get; set; }
    }
}
