//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS
{
    using System;
    using System.Collections.Generic;
    
    public partial class rpt_Purchases
    {
        public int ID { get; set; }
        public string Date { get; set; }
        public string ProdName { get; set; }
        public double Cost { get; set; }
        public int Quantity { get; set; }
        public double Total { get; set; }
        public int Invoice { get; set; }
    }
}
