//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        public int Sales_ID { get; set; }
        public int Product_FK { get; set; }
        public System.DateTime Date { get; set; }
        public string Customer_Name { get; set; }
        public string PaymentMethod { get; set; }
        public string Description { get; set; }
        public int Invoice { get; set; }
        public double Unit_Price { get; set; }
        public int Quantity { get; set; }
        public double Discount { get; set; }
        public double Misc { get; set; }
        public double Total { get; set; }
        public int User_FK { get; set; }
        public string Batch { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual User User { get; set; }
    }
}
